#!/bin/sh /etc/rc.common
USE_PROCD=1

START=99
STOP=50

NAME=vhusbd
PROG_DEF=/usr/bin/vhusbd
PROG_OPT=/usr/bin/vhusbd-optimized
CONF_DIR=/vfat0
CONF_FILE=${CONF_DIR}/vhusbd.ini
PIDFILE=/var/run/vhusbd.pid
CONF_DEV="/dev/mmcblk0p1"

_mount_fat() {
	if grep -qsF -e ${CONF_DEV} "/proc/mounts" ; then
		echo ${NAME} : ${CONF_DIR} already mount
	else
		echo ${NAME} : Mounting ${CONF_DEV} as ${CONF_DIR}
		mkdir --parent ${CONF_DIR}
		mount -o noatime,nodiratime,exec ${CONF_DEV} ${CONF_DIR}
		if [[ -e $CONF_FILE ]]; then
			echo ${NAME} : Creating $CONF_FILE
			touch $CONF_FILE
		fi
	fi
}

_should_use_optimized() {
	if grep -qsF -e "UseOptimized" $CONF_FILE ; then
		return 0
	fi
	return 1
}

_get_prog() {
	if _should_use_optimized ; then
		echo $PROG_OPT
	else 
		echo $PROG_DEF
	fi
}

start_service() {
	echo ${NAME} : Starting
	_mount_fat
	PROG=$( _get_prog )
	echo ${NAME} : Prog is ${PROG}
    procd_open_instance
	procd_set_param pidfile "$PIDFILE"
	procd_set_param nice "-10"
	procd_set_param stdout "1"
	procd_set_param stderr "1"
	procd_set_param file "$CONF_FILE"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} 0
    procd_set_param command "$PROG" 
	procd_append_param command -c "$CONF_FILE"
	procd_close_instance
	echo ${NAME} : Started
}
